### ISSUE TITLE
from_raw後にinto_rawが必要

### ISSUE THREAD

**Issue by ytakano** [Hotyoppi/dpdk-rust#1]
https://github.com/Hotyoppi/dpdk-rust/blob/054bf01d88744fafc0abbc6e85e4351e119d1ac9/rust/filter_modified/src/lib.rs#L320

一度、`from_raw`でArcをCからRustに変換したら、再び`into_raw`でRustからCに戻す必要がありそうです。

**Comment by Hotyoppi** [comment]
ありがとうございます。
解決しました。
